app/community/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError, Regexp
from app.models import Community

class NewCommunityForm(FlaskForm):
    name        = StringField('Name', validators=[DataRequired(), Length(max=128), Regexp('^[a-zA-Z][a-zA-Z0-9_]*$', flags=0, message='Name can contain only alphanumeric characters')])
    description = StringField('Description', validators=[DataRequired(), Length(max=512)])
    submit      = SubmitField('Create community')

    def validate_name(self, field):
        if Community.query.filter_by(name=field.data).first():
            raise ValidationError('Community with that name already exists')

class UpdateCommunityForm(FlaskForm):
    description = StringField('Description', validators=[DataRequired(), Length(max=512)])
    submit      = SubmitField('Update community')

app/communities/__init__.py
from flask import Blueprint

communities_blueprint = Blueprint('communities', __name__)

from app.communities import views

app/communities/views.py
from app.communities import communities_blueprint
from app.models import CommunityParticipant, Community
from flask import render_template

def join_or_leave(user, community):
    return CommunityParticipant.query.filter_by(community_id=community.id, user_id=user.id).first()

@communities_blueprint.route('/communities')
def communities():
    communities = Community.query.all()
    return render_template('communities/communities.html', communities=communities, join_or_leave=join_or_leave)

app/community/__init__.py
from flask import Blueprint

community_blueprint = Blueprint('community', __name__)

from app.community import views

app/community/views.py
from app.community import community_blueprint
from app.community.forms import NewCommunityForm, UpdateCommunityForm
from app import db
from app.models import Community, CommunityParticipant
from flask import render_template, redirect, url_for, flash, abort
from flask_login import login_required, current_user
from app.communities.views import join_or_leave

@community_blueprint.route('/community/r/<string:name>')
def get_community(name):
    community = Community.query.filter_by(name=name).first()
    if community:
        return render_template('community/get_community.html',community=community, join_or_leave=join_or_leave)
    else:
        abort(404)


@community_blueprint.route('/community/new', methods=['POST', 'GET'])
@login_required
def new_community():
    form = NewCommunityForm()
    if form.validate_on_submit():
        community = Community(name=form.name.data, description=form.description.data, user=current_user)
        db.session.add(community)
        db.session.commit()
        flash('Community created', 'success')
        return redirect(url_for('community.get_community', name=form.name.data))
    return render_template('community/new_community.html', form=form)

@community_blueprint.route('/community/update/<string:name>', methods=['POST', 'GET'])
@login_required
def update_community(name):
    form = UpdateCommunityForm()
    community = Community.query.filter_by(name=name).first()
    if form.validate_on_submit():
        community.description = form.description.data
        db.session.add(community)
        db.session.commit()
        flash('Community updated', 'success')
        return redirect(url_for('community.get_community', name=community.name))
    form.description.data   = community.description
    return render_template('community/update_community.html', form=form)

@community_blueprint.route('/community/delete/<string:name>')
@login_required
def delete_community(name):
    community = Community.query.filter_by(name=name).first()
    if community:
        if current_user.id == community.user.id:
            db.session.delete(community)
            db.session.commit()
            flash('Community deleted', 'danger')
            return redirect(url_for('main.home'))
        else:
            abort(403)
    else:
        abort(404)

@community_blueprint.route('/community/join/<string:name>')
@login_required
def join_community(name):
    community = Community.query.filter_by(name=name).first()
    if community:
        community_participant = CommunityParticipant.query.filter_by(user_id=current_user.id, community_id=community.id).first()
        if community_participant is None:
            community_participant = CommunityParticipant(community=community, user=current_user)
            db.session.add(community_participant)
            db.session.commit()
            flash(f'Joined r/{community.name} successfully', 'success')
            return redirect(url_for('community.get_community', name=community.name))
        else:
            flash(f'Already a member of r/{community.name}', 'primary')
            return redirect(url_for('community.get_community', name=community.name))
    else:
        abort(404)

@community_blueprint.route('/community/leave/<string:name>')
@login_required
def leave_community(name):
    community = Community.query.filter_by(name=name).first()
    if community:
        community_participant = CommunityParticipant.query.filter_by(user_id=current_user.id, community_id=community.id).first()
        if community_participant is None:
            flash(f'Cannot leave r/{community.name}, not a participant', 'danger')
            return redirect(url_for('community.get_community', name=community.name))
        else:
            db.session.delete(community_participant)
            db.session.commit()
            flash(f'Left r/{community.name}', 'danger')
            return redirect(url_for('community.get_community', name=community.name))
    else:
        abort(404)
    pass

app/templates/community/get_community.html
{% extends 'base.html' %}
{% block navbar %}
    {% if not current_user.is_anonymous and current_user.id == community.user.id %}
    {% if join_or_leave(current_user, community) %}
        <li class='nav-item'><a class='nav-link' href="{{ url_for('community.leave_community', name=community.name) }}">Leave community</a></li>
            {% else %}
        <li class='nav-item'><a class='nav-link' href="{{ url_for('community.join_community', name=community.name) }}">Join community</a></li>
        {% endif %}
<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More <i class='fas fa-chevron-circle-down'></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class='nav-link text-dark' href="{{ url_for('community.update_community', name=community.name) }}">Update community</a>
          <div class="dropdown-divider"></div>
        <a class='nav-link text-dark' href="{{ url_for('community.delete_community', name=community.name) }}">Delete community</a>
        </div>
      </li>

        <li class='nav-item'><a class='nav-link' href="{{ url_for('auth.logout') }}">Logout</a></li>
    {% elif current_user.is_authenticated %}
    {% if join_or_leave(current_user, community) %}
        <li class='nav-item'><a class='nav-link' href="{{ url_for('community.leave_community', name=community.name) }}">Leave community</a></li>
            {% else %}
        <li class='nav-item'><a class='nav-link' href="{{ url_for('community.join_community', name=community.name) }}">Join community</a></li>
        {% endif %}
        <li class='nav-item'><a class='nav-link' href="{{ url_for('auth.logout') }}">Logout</a></li>
    {% endif %}
{% endblock navbar %}
{% block content %}
    <div class='jumbotron'>
    <h2>Welcome to r/{{ community.name }}</h2>
    <p>{{ community.description }}</p>
    <p>Created by <a href="{{ url_for('main.profile', username=community.user.username) }}">
        u/{{ community.user.username }}
    </a>
    on {{ community.timestamp.strftime('%m/%d/%Y')}}
    </p>
    {% if join_or_leave(current_user, community) %}
        <a class='btn btn-danger' href="{{ url_for('community.leave_community', name=community.name) }}">Leave community</a>
            {% else %}
        <a class='btn btn-success' href="{{ url_for('community.join_community', name=community.name) }}">Join community</a>
        {% endif %}
    {% if current_user.is_authenticated %}
        <a class='btn btn-primary' href="{{ url_for('post.new_post', name=community.name) }}">New Post</a>
    {% endif %}
        <a class='btn btn-primary' href="{{ url_for('main.home') }}">Home</a>
</div>
<div class='jumbotron'>
    <h1>Participants</h1>
    {% for participant in community.participants %}
    <h4 class='img'><img src="{{ participant.user.gravatar() }}"><a class='text-decoration-none' href="{{ url_for('main.profile', username=participant.user.username) }}">
    u/{{ participant.user.username }}
</a></h4>
    {% endfor %}
</div>
{% endblock content %}

app/templates/community/new_community.html
{% extends 'base.html' %}
{% from 'macros/_fields.html' import fields %}
{% block content %}
    <form method='POST'>
        {{ form.hidden_tag() }}
        {{ fields(form.name) }}
        {{ fields(form.description) }}
        {{ form.submit(class='btn btn-primary') }}
    </form>
{% endblock content %}

app/templates/community/update_community.html
{% extends 'base.html' %}
{% from 'macros/_fields.html' import fields %}
{% block content %}
    <form method='POST'>
        {{ form.hidden_tag() }}
        {{ fields(form.description) }}
        {{ form.submit(clas='btn btn-primary') }}
    </form>
{% endblock content %}