app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField

class EditProfileForm(FlaskForm):
    name        = StringField('Name')
    location    = StringField('Location')
    about_me    = TextAreaField('About me')
    submit      = SubmitField('Update details')

app/main/__init__.py
from flask import Blueprint

main_blueprint = Blueprint('main', __name__)

from app.main import views

app/main/views.py
from app.main import main_blueprint
from flask import render_template, redirect, url_for, flash, abort
from flask_login import current_user, login_required
from app.main.forms import EditProfileForm
from app.models import User, CommunityParticipant, Post, Community
from app import db
from app.communities.views import join_or_leave

@main_blueprint.route('/')
def home():
    if current_user.is_authenticated:
        communities = CommunityParticipant.query.filter_by(user_id=current_user.id).all()
        posts = []
        for community in communities:
            posts += Post.query.filter_by(community_id = community.community_id).all()
    else:
        posts = Post.query.all()
    def find_community(xpost):
        post_community = Post.query.filter_by(title=xpost.title).first()
        community = Community.query.get(int(post_community.community_id))
        return community
    return render_template('main/home.html', posts=posts, find_community=find_community, hide_vote='yes')

@main_blueprint.route('/profile/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first()
    if user:
        return render_template('main/profile.html', user=user, join_or_leave=join_or_leave)
    else:
        abort(404)

@main_blueprint.route('/edit-profile/<username>', methods=['GET', 'POST'])
@login_required
def edit_profile(username):
    user = User.query.filter_by(username=username).first()
    form = EditProfileForm()
    if form.validate_on_submit():
        user.name       = form.name.data
        user.location   = form.location.data
        user.about_me   = form.about_me.data
        db.session.add(user)
        db.session.commit()
        flash('Account updated', 'success')
        return redirect(url_for('main.profile', username=user.username))
    form.name.data      = user.name
    form.location.data  = user.location
    form.about_me.data  = user.about_me
    return render_template('main/edit_profile.html', form=form)

app/templates/main/edit_profile.html
{% extends 'base.html' %}
{% from 'macros/_fields.html' import fields %}
{% block content %}
<form method='POST'>
    {{ form.hidden_tag() }}
    {{ fields(form.name) }}
    {{ fields(form.location) }}
    {{ fields(form.about_me) }}
    {{ form.submit(class='btn btn-primary') }}
</form>
{% endblock content %}

app/templates/main/home.html
{% extends 'base.html' %}
{% block messages %}
{% if not current_user.is_anonymous and not current_user.is_confirmed %}
<div class='container-sm mb-4'>
  {% include 'macros/_confirm.html' %}
</div>
{% endif %}
{% if current_user.is_anonymous %}
<div class='container-sm mb-4'>
  {% include 'macros/_register.html' %}
</div>
{% endif %}
{% endblock messages %}
{% block content %}
{% if posts %}
    {% for post in posts %}
    {% set community = find_community(post) %}
        {% include 'macros/_post.html' %}
    {% endfor %}
{% else %}
<h1 class='text-center'>Join some communties to view posts</h1>
<p class='text-center'><a class='btn btn-primary' href="{{ url_for('communities.communities') }}">View communities</a></p>
{% endif %}
{% endblock content %}

app/templates/main/profile.html
{% extends 'base.html' %}
{% block navbar %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More <i class='fas fa-chevron-circle-down'></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class='nav-link text-dark' href="{{ url_for('main.edit_profile', username=current_user.username) }}">Edit profile</a>
            <a class='nav-link text-dark' href="{{ url_for('auth.change_username') }}">Change username</a>
            <a class='nav-link text-dark' href="{{ url_for('auth.change_password') }}">Change password</a>
            <a class='nav-link text-dark' href="{{ url_for('auth.request_change_email') }}">Change email</a>
        </div>
    </li>
  <li class='nav-item'><a class='nav-link' href="{{ url_for('auth.logout') }}">Logout</a></li>
{% endblock navbar %}
{% block content %}
<div class='img jumbotron text-center'>
  <img src='{{ user.gravatar(size=256) }}' />
  <h4>u/{{ user.username }}</h4>
  <h4>{{ user.email }}</h4>
  {% if user.name %}
 <h4>Name {{ user.name }}</h4>
 {% endif %}
  {% if user.location %}
 <h4>Location {{ user.location }}</h4>
 {% endif %}
  {% if user.about_me %}
 <h4>About me {{ user.about_me }}</h4>
 {% endif %}
 {% if current_user.id == user.id %}
 <a class='btn btn-primary' href="{{ url_for('main.edit_profile', username=user.username) }}">Edit profile</a>
 {% endif %}
 <a class='btn btn-primary' href="#community">Communities</a>
 <a class='btn btn-primary' href="#posts">Posts</a>
</div>
<h2 id='community'>Communities</h2>
  {% for community in user.communities %}
  <div class='jumbotron'>
  <a href="url_for('community.get_community', name=community.name) }}">
    <h2> r/{{ community.name }}</h2>
    <p>{{ community.description }}</p>
    <p>Created by <a href="{{ url_for('main.profile', username=community.user.username) }}">
        u/{{ community.user.username }}
    </a>
    on {{ community.timestamp.strftime('%m/%d/%Y')}}
    </p>
  </a>
    {% if join_or_leave(current_user, community) %}
        <a class='btn btn-danger' href="{{ url_for('community.leave_community', name=community.name) }}">Leave community</a>
            {% else %}
        <a class='btn btn-success' href="{{ url_for('community.join_community', name=community.name) }}">Join community</a>
        {% endif %}
        <a class='btn btn-primary' href="{{ url_for('main.home') }}">Home</a>
  </div>
  {% endfor %}

<h2 id='posts'>Posts by u/{{ user.username }}</h2>
{% for post in user.posts %}
{% set community=post.community %}
{% include 'macros/_post.html' %}
{% endfor %}
{% endblock content %}