app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, Regexp, ValidationError
from app.models import Post

class NewPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(max=256), Regexp('^[a-zA-Z][a-zA-Z0-9- ]*$', flags=0, message='Can only use aphanumeric characters and space')])
    body = TextAreaField('Body', validators=[DataRequired()])
    submit = SubmitField('Post')

    def validate_title(self, field):
        if Post.query.filter_by(title=field.data).first():
            raise ValidationError('Post with that title already exists')

class UpdatePostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(max=256), Regexp('^[a-zA-Z][a-zA-Z0-9- ]*$', flags=0, message='Can only use aphanumeric characters and space')])
    body = TextAreaField('Body', validators=[DataRequired()])
    submit = SubmitField('Post')

    def validate_title(self, field):
        if Post.query.filter_by(title=field.data).first():
            raise ValidationError('Post with that title already exists')

app/reply/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired

class NewReplyForm(FlaskForm):
    body = TextAreaField('Reply', validators=[DataRequired()])
    submit = SubmitField('Reply')

class EditReplyForm(FlaskForm):
    body = TextAreaField('Reply', validators=[DataRequired()])
    submit = SubmitField('Reply')

app/post/__init__.py
from flask import Blueprint

post_blueprint = Blueprint('post', __name__)

from app.post import views

app/post/views.py
from flask import render_template, redirect, url_for, abort, flash
from flask_login import current_user, login_required
from app.post import post_blueprint
from app import db
from app.models import Community, Post, PostVote, Reply, ReplyVote
from app.post.forms import NewPostForm, UpdatePostForm
from app.communities.views import join_or_leave

@post_blueprint.route('/community/r/<string:name>/posts')
def get_posts(name):
    community = Community.query.filter_by(name=name).first()
    if community:
        posts = Post.query.filter_by(community=community).all()
        return render_template('post/get_posts.html', posts=posts, community=community, join_or_leave=join_or_leave)
    else:
        abort(404)

@post_blueprint.route('/community/r/<string:name>/get/<string:title>')
def get_post(name, title):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post:
            replies = Reply.query.filter_by(post_id=post.id)
            post_votes = PostVote.query.filter_by(post_id=post.id).all()
            sum = 0
            for post_vote in post_votes:
                sum += post_vote.count
            def get_votes(reply):
                replies = ReplyVote.query.filter_by(reply_id=reply.id).all()
                sum = 0
                for reply in replies:
                    sum += reply.count
                return sum
            return render_template('post/get_post.html', post=post, community=community, get_votes=get_votes,post_vote=sum, replies=replies, hide_view='yes')
        else:
            abort(404)
    else:
        abort(404)

@post_blueprint.route('/community/r/<string:name>/post', methods=['GET', 'POST'])
@login_required
def new_post(name):
    community = Community.query.filter_by(name=name).first()
    if community:
        form = NewPostForm()
        if form.validate_on_submit():
            post = Post(title=form.title.data, body=form.body.data, author=current_user, community=community)
            post.remove_space_from_title()
            db.session.commit()
            flash(f'Posted on r/{community.name}', 'success')
            return redirect(url_for('post.get_post', name=community.name, title=post.title))
        return render_template('post/new_post.html', form=form)
    else:
        abort(404)

@post_blueprint.route('/community/r/<string:name>/edit/<string:title>', methods=['GET', 'POST'])
@login_required
def update_post(name, title):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post and post.author.id == current_user.id:
            form = UpdatePostForm()
            if form.validate_on_submit():
                post.title  = form.title.data
                post.body   = form.body.data
                post.remove_space_from_title()
                db.session.commit()
                flash('Post edited', 'primary')
                return redirect(url_for('post.get_post', name=community.name, title=post.title))
            form.title.data = post.title
            form.body.data  = post.body
            return render_template('post/update_post.html', form=form)
        else:
            abort(404)
    else:
        abort(404)

@post_blueprint.route('/community/r/<string:name>/delete/<string:title>')
@login_required
def delete_post(name, title):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post and post.author.id == current_user.id:
            db.session.delete(post)
            db.session.commit()
            flash('Post deleted')
            return redirect(url_for('community.get_community', name=community.name))
        else:
            abort(404)
    else:
        abort(404)

@post_blueprint.route('/community/r/<string:name>/upvote/<string:title>')
@login_required
def upvote_post(name, title):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post:
            post_vote = PostVote.query.filter_by(post_id=post.id, user_id=current_user.id).first()
            if post_vote is None:
                post_vote = PostVote(user_id=current_user.id, post_id=post.id, count=1)
                db.session.add(post_vote)
            elif abs(post_vote.count) == 1:
                post_vote.count=0
            else:
                post_vote.count = 1
            db.session.commit()
            return redirect(url_for('post.get_post', name=community.name, title=post.title))
        else:
            abort(404)
    else:
        abort(404)

@post_blueprint.route('/community/r/<string:name>/downvote/<string:title>')
@login_required
def downvote_post(name, title):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post:
            post_vote = PostVote.query.filter_by(post_id=post.id, user_id=current_user.id).first()
            if post_vote is None:
                post_vote = PostVote(user_id=current_user.id, post_id=post.id, count=-1)
                db.session.add(post_vote)
            elif abs(post_vote.count) == 1:
                post_vote.count=0
            else:
                post_vote.count = -1
            db.session.commit()
            return redirect(url_for('post.get_post', name=community.name, title=post.title))
        else:
            abort(404)
    else:
        abort(404)

app/reply/__init__.py
from flask import Blueprint

reply_blueprint = Blueprint('reply', __name__)

from app.reply import views

app/reply/views.py
from app.reply import reply_blueprint
from flask import render_template, redirect, url_for, abort, flash
from app.models import Reply, ReplyVote, Community, Post
from app.reply.forms import NewReplyForm, EditReplyForm
from flask_login import current_user
from app import db

@reply_blueprint.route('/community/r/<string:name>/get/<string:title>/reply', methods=['GET', 'POST'])
def new_reply(name, title):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post:
            form=NewReplyForm()
            if form.validate_on_submit():
                reply = Reply(body=form.body.data, author=current_user, post=post)
                db.session.add(reply)
                db.session.commit()
                flash('Commented on post', 'primary')
                return redirect(url_for('post.get_post', name=community.name, title=post.title))
            return render_template('reply/new_reply.html', form=form)
        else:
            abort(404)
    else:
        abort(404)
@reply_blueprint.route('/community/r/<string:name>/get/<string:title>/reply/edit/<int:reply_id>', methods=['GET', 'POST'])
def edit_reply(name, title, reply_id):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post:
            reply = Reply.query.get(int(reply_id))
            if reply and reply.author.id == current_user.id:
                form=EditReplyForm()
                if form.validate_on_submit():
                    reply.body = form.body.data
                    db.session.add(reply)
                    db.session.commit()
                    flash('Reply edited', 'primary')
                    return redirect(url_for('post.get_post', name=community.name, title=post.title))
                form.body.data = reply.body
                return render_template('reply/edit_reply.html', form=form)
            else:
                abort(404)
        else:
            abort(404)
    else:
        abort(404)

@reply_blueprint.route('/community/r/<string:name>/get/<string:title>/reply/delete/<int:reply_id>')
def delete_reply(name, title, reply_id):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post:
            reply = Reply.query.get(int(reply_id))
            if reply and reply.author.id == current_user.id:
                db.session.delete(reply)
                db.session.commit()
                flash('Reply deleted', 'danger')
                return redirect(url_for('post.get_post', name=community.name, title=post.title))
            else:
                abort(404)
        else:
            abort(404)
    else:
        abort(404)

@reply_blueprint.route('/community/r/<string:name>/get/<string:title>/reply/upvote/<int:reply_id>')
def upvote_reply(name, title, reply_id):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post:
            reply = Reply.query.get(int(reply_id))
            if reply:
                reply_vote = ReplyVote.query.filter_by(reply_id=reply_id, user_id=current_user.id).first()
                print(reply_vote)
                if reply_vote is None:
                    reply_vote = ReplyVote(user_id=current_user.id, reply_id=reply.id, count=1)
                    db.session.add(reply_vote)
                elif (reply_vote.count) == 1:
                    reply_vote.count = 0
                else:
                    reply_vote.count=1
                db.session.commit()
                return redirect(url_for('post.get_post', name=community.name, title=post.title))
            else:
                abort(404)
        else:
            abort(404)
    else:
        abort(404)

@reply_blueprint.route('/community/r/<string:name>/get/<string:title>/reply/downvote/<int:reply_id>')
def downvote_reply(name, title, reply_id):
    community = Community.query.filter_by(name=name).first()
    if community:
        post = Post.query.filter_by(title=title).first()
        if post:
            reply = Reply.query.get(int(reply_id))
            if reply:
                reply_vote = ReplyVote.query.filter_by(reply_id=reply_id, user_id=current_user.id).first()
                if reply_vote is None:
                    reply_vote = ReplyVote(user_id=current_user.id, reply_id=reply.id, count=-1)
                    db.session.add(reply_vote)
                elif (reply_vote.count) == -1:
                    reply_vote.count = 0
                else:
                    reply_vote.count=-1
                db.session.commit()
                return redirect(url_for('post.get_post', name=community.name, title=post.title))
            else:
                abort(404)
        else:
            abort(404)
    else:
        abort(404)

app/templates/macros/_confirm.html
<div class='text-center'>
    Confirm your email to use the app without constraints <a href="{{ url_for('auth.get_confirmation_token') }}"><button class='btn btn-primary'>Confirm</button></a>
</div>

app/templates/macros/_fields.html
{% macro fields(field, remember=False) %}
    {% if remember==True %}
    <div class='form-group'>
        {{ field.label }}
        {% if field.errors %}
        {{ field }}
        <div>
        {% for error in field.errors %}
        <span>{{ error }}</span>
        {% endfor %}
        </div>
        {% else %}
        {{ field }}
        {% endif %}
    </div>

    {% else %}
    <div class='form-group'>
        {{ field.label }}
        {% if field.errors %}
        {{ field(class='form-control is-invalid') }}
        <div>
        {% for error in field.errors %}
        <span>{{ error }}</span>
        {% endfor %}
        </div>
        {% else %}
        {{ field(class='form-control') }}
        {% endif %}
    </div>
    {% endif %}
{% endmacro  %}

app/templates/macros/_post.html
<div class='jumbotron'>
    <a class='img' href="{{ url_for('main.profile', username=post.author.username) }}">
    <img src="{{ post.author.gravatar() }}">
    </a>
    <p>Posted by
    <a href="{{ url_for('main.profile', username=post.author.username) }}">
    u/{{ post.author.username }}
    </a> in
    <a href="{{ url_for('community.get_community', name=community.name) }}">r/{{ community.name }}</a> on {{ post.timestamp.strftime("%m/%d/%Y") }}</p>
    </a>
</p>
    <h3>{{ post.title }}</h3>
    <p>{{ post.body }}</p>
    <p class='font-match'>
    {% if not current_user.is_authenticated %}
    {{ post_vote }}
    <a class='btn btn-primary' href="{{ url_for('auth.login') }}">Login to vote</a>
    {% endif %}
    {% if current_user.is_authenticated %}
    {% if not hide_vote %}
    <a href="{{ url_for('post.upvote_post', name=community.name, title=post.title) }}"><i class='fas fa-arrow-alt-circle-up'></i></a>
    {% if not post_vote or post_vote == 0 %}
        {{ 0 }}
    {% else %}
    {{ post_vote }}
    {% endif %}
    <a href="{{ url_for('post.downvote_post', name=community.name, title=post.title) }}"><i class='fas fa-arrow-alt-circle-down'></i></a>
    {% endif %}
    {% endif %}
    </p>
    {% if hide_view != 'yes' %}
    <a class='btn btn-primary' href="{{ url_for('post.get_post', name=community.name, title=post.title) }}">View post</a>
    {% endif %}
    {% if current_user.is_authenticated %}
    <a class='btn btn-primary' href="{{ url_for('reply.new_reply', name=community.name, title=post.title) }}">Reply</a>
    {% endif %}
{% if current_user.id == post.author.id %}
    <a class='btn btn-primary' href="{{ url_for('post.update_post', name=community.name, title=post.title) }}">Update post</a>
    <a class='btn btn-danger' href="{{ url_for('post.delete_post', name=community.name, title=post.title) }}">Delete post</a>
{% endif %}
</div>

app/templates/macros/_register.html
<div class='text-center'>
    Create an account or login to use the app without constraints
    <a href="{{ url_for('auth.register') }}"><button class='btn btn-primary'>Register</button></a>
    <a href="{{ url_for('auth.login') }}"><button class='btn btn-primary'>Login</button></a>
</div>

app/templates/macros/_reply.html
    <div class='jumbotron'>
        <a class='img' href="{{ url_for('main.profile', username=reply.author.username) }}">
        <img src="{{ reply.author.gravatar() }}">
        <p>
        u/{{ reply.author.username }}</a> replied in <a href="{{ url_for('community.get_community', name=community.name) }}">r/{{ community.name }}</a> on {{ reply.timestamp.strftime('%m/%d/%Y') }}
        <p>{{ reply.body }}</p>
        <p class='font-match'>
        {% if not current_user.is_anonymous %}
        <a href="{{ url_for('reply.upvote_reply', name=community.name, title=post.title, reply_id=reply.id) }}"><i class='fas fa-arrow-alt-circle-up '></i></a>
        {{ get_votes(reply=reply) }}
        <a href="{{ url_for('reply.downvote_reply', name=community.name, title=post.title, reply_id=reply.id) }}"><i class='fas fa-arrow-alt-circle-down '></i></a>
        {% else %}
        {{ get_votes(reply=reply) }}
        <a class='btn btn-primary' href="{{ url_for('auth.login') }}">Login to vote</a>
        {% endif %}
    </p>
        {% if reply.author.id == current_user.id %}
        <a class='btn btn-primary' href="{{ url_for('reply.edit_reply', name=community.name, title=post.title, reply_id=reply.id) }}">Edit</a>
        <a class='btn btn-danger' href="{{ url_for('reply.delete_reply', name=community.name, title=post.title, reply_id=reply.id) }}">Delete</a>
        {% endif %}
    </div>